apiVersion: v1
kind: Service
metadata:
  name: task101p-load-balancer-service
spec:
  type: LoadBalancer
  selector:
    type: backend
    app: task101p
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000